# Setup
title:            'Mohammad AbuShady'
description:      'A simple jekyll blog'
tagline:          'Software Developer'
url:              'http://blog.abushady.com'
baseurl:          /

# pagination
paginate:         5
paginate_path:    'page:num'

markdown: rdiscount
permalink: date
highligher: true

exclude: [Gemfile, Gemfile.lock, CNAME, atlassian-ide-plugin.xml]
timezone: Africa/Cairo

author:
  name:           'Mohammad AbuShady'
  url:            'mohammad.abushady.com'

theme:        https://github.com/poole/hyde

disqus:
  shortname: 'coalwater'
