# Setup
title:            'Mohammad AbuShady'
description:      A software developer, mainly using ruby/rails,
                  using this blog to write about every thing i found useful
tagline:          'Software Developer'
url:              'http://blog.abushady.com'
baseurl:          /

# pagination
paginate:         5
paginate_path:    'page:num'

markdown: rdiscount
permalink: date
highligher: true

exclude: [Gemfile, Gemfile.lock, CNAME, atlassian-ide-plugin.xml]
timezone: Africa/Cairo

author:
  name:           'Mohammad AbuShady'
  url:            'mohammad.abushady.com'

theme:        https://github.com/poole/hyde

links:
  - name: Github
    url: http://url.abushady.com/github
    icon: 'fa fa-github'
  - name: StackOverflow
    url: http://url.abushady.com/stackoverflow
    icon: 'fa fa-stack-overflow'
  - name: LinkedIn
    url: http://url.abushady.com/linkedin
    icon: 'fa fa-linkedin'

disqus:
  shortname: 'coalwater'
