# Setup
title:            'Mohammad AbuShady'
description:      I'm a software developer, mainly using ruby/rails, using this
                  blog to write about my experiencnes and every thing i find
                  useful.
tagline:          'Software Developer'
url:              'http://blog.abushady.com'
baseurl:          /

repo_url:         https://github.com/coalwater/blog.abushady.com

read_more:        'Continue reading'

# pagination
paginate:         5
paginate_path:    'page:num'

excerpt_separator: <!-- more -->

markdown: kramdown
permalink: date
highligher: true

exclude: [Gemfile, Gemfile.lock, CNAME, atlassian-ide-plugin.xml]
timezone: Africa/Cairo

author:
  name:           'Mohammad AbuShady'
  url:            'https://github.com/coalwater/'
  email:          'blog@abushady.com'

my_theme:
  repo:           https://github.com/poole/lanyon
  name:           lanyon

links:
  - name: Github
    url: https://github.com/coalwater
    icon: 'fa fa-github'
  - name: StackOverflow
    url: http://stackoverflow.com/users/2149092/mohammad-abushady
    icon: 'fa fa-stack-overflow'
  - name: LinkedIn
    url: https://www.linkedin.com/in/mohammadabushady
    icon: 'fa fa-linkedin'

about_me_footer_links:
  - name: Github
    url: https://github.com/coalwater
    icon: 'fa fa-github'
  - name: StackOverflow
    url: http://stackoverflow.com/users/2149092/mohammad-abushady
    icon: 'fa fa-stack-overflow'
  - name: LinkedIn
    url: https://www.linkedin.com/in/mohammadabushady
    icon: 'fa fa-linkedin'
  - name: Dot files
    url: https://github.com/coalwater/dotfiles
    icon: 'fa fa-file-text-o'
  - name: Hire me
    url: https://www.upwork.com/freelancers/~017d64b3de125aeff1
    icon: 'fas fa-briefcase'

gems:
  - jekyll-paginate
  - jekyll-gist

disqus:
  shortname: 'coalwater'
